config/routes.rb
Rails.application.routes.draw do
  root "home#index", as: "home"
  resources :sessions
  resources :users do
    resources :tasks
  end

  get "/login", to: "sessions#new"
  get "/logout", to: "sessions#destroy"
  get "/about", to: "about_us#index"
end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :user
  validates :name, presence: true
  validates :location, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  validates :username, presence: true, uniqueness: true
  validates :location, presence: true
  VALID_EMAIL_REGEX = /\w+@[^\.]+\.\w+/
  validates :email,
            presence:   true,
            format:     { with: VALID_EMAIL_REGEX },
            uniqueness: true,
            length:     { maximum: 255 }
  validates :password, presence: true, length: { minimum: 8 }

  has_secure_password
  has_many :tasks

  def self.confirm(params)
    @user = User.find_by({email: params[:email]})
    @user.try(:authenticate, params[:password])
  end

end

app/controllers/about_us_controller.rb
class AboutUsController < ApplicationController
  def index
    render :index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    if current_user
      @user = current_user
      @tasks = @user.tasks
    end
    render :index
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def create
    user_params = params.require(:user).permit(:email, :password)
    @user = User.confirm(user_params)
    if @user
      login(@user)
      redirect_to @user
    else
      flash[:error] = "No user found!"
      redirect_to home_path
    end
  end

  def destroy
    logout  
    flash[:notice] = "Successfully logged out."
    redirect_to home_path
  end
  def testing
    1+2
  end

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  def new
    @task = Task.new
    @user = User.find(params[:user_id])
    if current_user
      render :new
    else
      flash[:error] = "Could not create task"
      redirect_to home_path
    end
  end

  def create
    @task = Task.create(task_params)
    @user = current_user
    @user.tasks << @task
    flash[:success] = "Task created!"
    redirect_to user_path(@user)
  end

  def edit
    @task = Task.find(params[:id])
    @user = @task.user
    if current_user == @user
      render :edit
    else
   flash[:error] = "Must log in to edit!"
      redirect_to home_path
    end
  end

  def update
    @user = User.find(params[:user_id])
    @task = Task.find(params[:id])
    @task.update(task_params)
    flash[:success] = "Task update complete!"
    redirect_to @user
  end

  def destroy
    @task = Task.find(params[:id])
    @user = @task.user
    if current_user == @user
      @user.tasks.destroy(@task)
      flash[:success] = "Task deleted!"
      redirect_to @user
    else
      flash[:error] = "Must log in to delete task"
      redirect_to home_path
    end
  end


  private

  def task_params
    params.require(:task).permit(:name, :location)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
    render :new
  end

  def create
    @user = User.create(user_params)
    if @user.image == ""
      @user.image = "photo.jpg"
    end
    if @user.save
      login(@user)
      redirect_to user_path(@user)
    else
      render :new
    end
  end

  def show
    @user = User.find_by_id(params[:id])
    @tasks = @user.tasks
    if current_user == @user
      render :show
    else
      redirect_to home_path
    end

  end

  private

  def user_params
    params.require(:user).permit(:username, :email, :password, :location, :image)
  end

end

app/helpers/about_us_helper.rb
module AboutUsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def login(user)
    session[:user_id] = user.id
    @current_user = user
  end

  def current_user
    @current_user ||= User.find_by_id(session[:user_id])
  end

  def logged_in?
    if current_user == nil
      redirect_to new_session_path
    end
  end

  def logout
    @current_user = session[:user_id] = nil
  end

end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/about_us/index.html.erb
<div class="container pad-down">
  <h1 class="head">We're no strangers to code.</h1>
  <div class="row">
    <div class="col-sm-3">
      <%= image_tag "rusham.jpg", class:"aboutUsPic" %>
      <h3 class="name">John</h3>
      <p class="bio">(Said in one breath) John “Face Like a Sunset” Ruhsam has been described as 60% Battle Cat, 30% protein powder, and 20% pure excellence. That’s 10% extra of a 178 lbs hunk o’ man because we don’t half ass anything here at @SomePoint. This project peaked John’s interest when he realized he could go to the gym, the laundromat (because he’s not stanky people) back to the gym, then to his waxing appointment efficiently and optimized as F*Bomb. This Buffalo blanketless sweet piece of meat is as handsome as he is productive in a TDD environment ripe with Rspec loving. #concatenation</p>
    </div>
    <div class="col-sm-3">
      <%= image_tag "paul.jpg", class:"aboutUsPic" %>
      <h3 class="name">Paul</h3>
      <p class="bio">CSS, stands for Cleary's Superior Styling. There is no Margin for error here, so give me some Padding. When you're on the Top you can see all the way to the Border but you can't realy see the Height. It is a Relative Position. It almost feels like your Floating, it's quite a Display. Don't go too far though, you might Overflow. Thats about all that needed to be Covered. I'm out! #z-index.</p>
    </div>
    <div class="col-sm-3">
      <%= image_tag "rails.png", class:"aboutUsPic" %>
      <h3 class="name">Jonny Rails</h3>
      <p class="bio">Jonny Rails is a pirate Blustering in from sea, With a rollicking song, he sweeps along, Swaggering boisterously. His branch has merge conflicts. He wears a hooded sash, With a warriors hat about his head, And a bristling black mustache. He growls as he storms the commons, A villain big with code. Jonny Rails Pillages just for fun. Useing Rails or Node.
      </p>
    </div>
    <div class="col-sm-3">
      <%= image_tag "justin.png", class:"aboutUsPic" %>
      <h3 class="name">Justin</h3>
      <p class="bio">Who, what, where, when, why, how. It’s kind of what I’m about. If we need a controller, I’m there. If we need to change databases, I’m on it. Heroku givin’ you problems? I’ve got the Chuck Norris beard punch that traverses the ether and the time space continuum. When things get sideways, I’ve got the level. Wether it’s getting data in or data coming out, I’ll concatenate your strings, parse out your ids and dot method your JSON to death. My entrancing gaze puts your pin on the map, with or without your google maps API key. </p>
    </div>
</div>
  <legend></legend>
  <div class="row">
    <h1 class="name">About Our App</h1>
    <p class="aboutApp">You think water moves fast? You should see ice. It moves like it has a mind. Like it knows it killed the world once and got a taste for murder. After the avalanche, it took us a week to climb out. Now, I don't know exactly when we turned on each other, but I know that seven of us survived the slide... and only five made it out. Now we took an oath, that I'm breaking now. We said we'd say it was the snow that killed the other two, but it wasn't. Nature is lethal but it doesn't hold a candle to man. </p>

  </div>
  <div class="row">
      <%= link_to (image_tag ("sponsors.png"), class: "sponsors"), "https://fast-crag-58604.herokuapp.com/" %>
  </div>
</div>

<div id="vid"></div>

<script>
$(document).on("ready", function(){
    console.log(this);
    $('#vid').append('<iframe width="420" height="315" src="https://www.youtube.com/embed/dQw4w9WgXcQ?autoplay=1" frameborder="0" allowfullscreen></iframe>')
    $('body').css( "background-color", "thistle" );
    $('#vid').hide();
  });
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AtSomePoint</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= favicon_link_tag 'http://the1perspective.com/jonatron/somepoint.ico' %>
</head>
<body>
  <nav class="navbar navbar-default navbar-fixed-top">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <div class="navbar-brand">
          <%= link_to image_tag("cargif.gif"), home_path, class:"img-brand" %>
        </div>
      </div>
      <div id="navbar" class="navbar-collapse collapse">
        <% if current_user %>
          <ul class="nav navbar-nav">
            <li><%= link_to "Profile", user_path(current_user) %></li>
            <li><%= link_to "Log Out", logout_path %></li>
          </ul>
        <% else %>
          <%= form_for :user, url: "/sessions", method: "post", :html => {:class => "navbar-form navbar-right"} do |f| %>
            <div class="form-group">
              Email:
              <%= f.text_field :email, value: "Sample@login.com", class: "form-control" %>
            </div>
            <div class="form-group">
              Password:
              <%= f.password_field :password, value: "aaaaaaaa", class: "form-control" %>
            </div>
            <div class="form-group">
              <%= f.submit "Log In", class: "btn btn-success" %>
            </div>
          <% end %>
        <% end %>
        <% if current_user %>
          <ul class="nav navbar-nav navbar-right">
            <li><div class="navbar-brand logged">Logged in as: <%= current_user.username %></div></li>
          </ul>
        <% end %>
      </div><!--/.navbar-collapse -->
    </div>
  </nav>
  <% flash.each do |name, msg| %>
    <div class="alert alert-dismissible alert-info flash" id="flash">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      <span class="sr-only">Oh snap!</span>
      <%= msg %>
    </div>
    <script type="text/javascript">
    $(document).ready(function(){
      setTimeout(function(){
        $('#flash').remove();
      }, 3000);
    })
    </script>
  <% end %>


  <!-- Begin page content -->
  <%= yield %>

  <footer class="footer about-foot">
    <div class="container">
      <h6>2016 @somepoint all rights reserved</h6>
      <%= button_to "-About-", about_path, method: "get", class:"btn btn-xs btn-success btn-push" %>
    </div>
  </footer>

</body>
</html>

app/views/tasks/edit.html.erb
<% if @user == current_user %>
<br>
<h1>LETS EDIT!</h1>
<div class="container pad-down">
    <%= simple_form_for :task, url: user_task_path(@user,@task), method: "patch" do |f| %>
    <%= f.input :name, placeholder: 'example: pick up the kids' %>
    <%= f.input :location, inline_label: 'Enter Valid Address' %>
    <%= f.button :submit %>
  <% end %>
</div>
<% else %>
  <h1 class="denied"> <%= current_user.username %> is not authorized to view this page. </h1>
<% end %>

app/views/tasks/new.html.erb
<% if @user == current_user %>
<div class="container">
  <div class="row">
    <div class="col-md-6 col-md-offset-3 col-xs-6 col-xs-offset-3">
      <img class="featurette-image img-responsive center-block logo-form" src="http://the1perspective.com/jonatron/cargif.gif" alt="Generic placeholder image">
      <%= simple_form_for :task, url: user_tasks_path(@user), method: "post" do |f| %>
      <%= f.input :name, required: true, placeholder: 'example: pick up the kids' %>
      <%= f.input :location, required: true, inline_label: 'Enter Valid Address' %>
      <%= f.button :submit, class: "btn btn-info btn-block" %>
      <% end %>
    </div>
  </div>
</div>
<% else %>
<h1 class="denied"> <%= current_user.username %> is not authorized to view this page. </h1>
<% end %>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-12">
      this is a test

    </div>

  </div>

</div>

app/views/users/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-6 col-md-offset-3 col-xs-10 col-xs-offset-1">
      <img class="featurette-image img-responsive center-block logo-form" src="http://the1perspective.com/jonatron/cargif.gif" alt="Generic placeholder image">
      <%= simple_form_for @user do |f| %>
      <%= f.input :username, label: 'Username' %>
      <%= f.input :email, placeholer: 'user@domain.com' %>
      <%= f.input :image, placeholder: 'image/url' %>
      <%= f.input :location %>
      <%= f.input :password, hint: 'Password Must Be > 7 characters' %>
      <%= f.button :submit, class: 'btn btn-warning btn-block btn-md' %>
      <% end %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<% if @user == current_user %>
<div class="container">
  <div class="row">
    <div class="col-md-6 col-md-offset-3 col-lg-8 col-lg-offset-2">
    <div class="thumbnail">
      <%= image_tag current_user.image, class: "img-center img-responsive fix-img profile-img" %>
      <div class="caption">
        <p><%= @user.email %></p>
        <p>Joined On: <%= @user.created_at.strftime("%b %d, %Y") %></p>
        <% if @user.tasks.count >= 1 %>
        <%= link_to "GO!", "/", class: "btn btn-success btn-block btn-md" %>
        <% end %>
        <%= link_to "New Task", new_user_task_path(@user), class: "btn btn-info btn-block btn-md" %>
      </div>
    </div>
  </div>
</div>



  <div class="row">
    <div class="col-md-6 col-md-offset-3 col-lg-8 col-lg-offset-2">
      <table class="table table-hover">
        <% if @user.tasks.length > 0 %>
        <tr id="table-head">
          <th>Todo: </th>
        </tr>
        <% end %>
        <% @tasks.each do |task| %>
        <tbody class="tasks">
          <tr id="singleTask">
            <td><%= task.name %></td>
            <td><%= task.location %></td>
            <td>
              <%= link_to "Edit", edit_user_task_path(@user, task), :method => :get, class: "btn btn-warning btn-block btn-xs" %>
            </td>
            <td>
              <%= button_to "Delete", user_task_path(@user, task), remote: true, method: 'delete', class: "btn btn-danger delete-button btn-block btn-xs" %>
            </td>
          </tr>
        </tbody>
        <% end %>
      </table>
    </div>
  </div>



  </div>
  <% elsif %>
  <div class="container">
    <% if !current_user == current_user %>
    <%= current_user.username %> is not authorized to view this page.

    <% end %>
  </div>
  <div class="container">
    <% else %>You are not authorized to view this page.

  </div>


<% end %>